version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #git-credential-helper: yes

phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
      docker: 18
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-1)
      - cd docker
      - echo Local dir
      - pwd
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t cod01:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker tag cod01:$CODEBUILD_RESOLVED_SOURCE_VERSION 683590979119.dkr.ecr.eu-west-1.amazonaws.com/cod01:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 683590979119.dkr.ecr.eu-west-1.amazonaws.com/cod01:$CODEBUILD_RESOLVED_SOURCE_VERSION

#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths

